// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_addpackages.cpp"
#include "EWIEGA46WW/moc_findpackage.cpp"
#include "EWIEGA46WW/moc_findtourist.cpp"
#include "EWIEGA46WW/moc_mainwindow.cpp"
#include "EWIEGA46WW/moc_registertourist.cpp"
